language: c
matrix:
  include:
    - os: linux
      env:
        - PIP='sudo pip'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
    - os: osx

before_script:
  - sh "./tiny-firmware/protob/ci-scripts/install-${TRAVIS_OS_NAME}.sh" ;
  # Define env vars for Linux builds
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    ls -l /usr/local/bin/protoc ;
    export CHECK_PATH="$(pwd)/check-0.12.0" ;
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${CHECK_PATH}/src" ;
    export PATH="/usr/local/bin:$(pwd)/protoc/bin:$PATH" ;
    echo "PATH=$PATH";
    echo "PIP=$PIP";
    fi
  # Define env vars for osx builds
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    export CHECK_PATH="$(brew --prefix check)" ;
    export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${CHECK_PATH}/lib" ;
    fi
  # Install OS-specific test and build dependencies
  - eval "./ci-scripts/install-${TRAVIS_OS_NAME}.sh"
  # Install linters
  - make install-linters

script:
  - make verify-protob-hash
  - make lint
  - make -C tiny-firmware/protob build-c
  - make test
  - make clean
  - make emulator
  - make clean
  - make full-firmware
  - make clean
  - if [[ $TRAVIS_TAG != '' ]]; then
    make release;
    VERSION_BOOTLOADER=$(cat tiny-firmware/bootloader/VERSION);
    ID_VENDOR=12602;
    ID_PRODUCT=1;
    export COMBINED_VERSION=${VERSION_BOOTLOADER}-${TRAVIS_TAG}-${ID_VENDOR}-${ID_PRODUCT}-1;
    fi
notifications:
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
- provider: releases
  api_key:
    secure: vG42CO+JU1gGv2mFl9EIgzHh5f17ceTs9nHJzL2JTGs5bWkMVsaeVB235wHjMsYZ0uQ1DEhk0eoYCq2cS8pl/Q/8TYufSKo0XiSv6ySPUIzYi4YDkAfMnuXlNlP5Adm9UeI+jISp14sbjnHXTD+pBIalAOCaebqGQBtSvIwAkwOnG4arubDiNIoho/q/vHkLRaqiGkgP7pnujtCb1Z4OQCro9FOpMaNcNXsG7LGuabdtvMpzFlzRmvrSzPJiF7f8Db+LjcBkuneeacIg/Bgpd1X2i98Tv9Ytv8IIsd0WrCfKgTp/YYxDS0u1Bn25EGomac0gSvXiYJ1hDtqn58AY1AXuM5ibVJAu5JOBgGqTkRvrLN4WFoRIrUW10i8ArsVxPh5lWJvtjkYNDMtFhHVBCpTyNnTR/OSLGTkRGYBWuoJRW8h3bR6fmP7WrGyVhKIOgklmv6cPGTI6wUAk5KMvFCpHbhATfkTXVj3f0aZEwae7Eho5KgAIPsnKkZlNEq0y+GMj1LMdEE5Leb78gT7dC5R7p/0YD43WPL/YIA3sBAVFYdE0YTa/0jYn5SBFStGskV8vwGwtRopoV4DR6sGfg5SY6ctM5HVAczcm456k1t8rLmSdZ47XZFvcjg5YgV7Eo2D/1IYpAIKlnnfQ0jklcw6tTd6uWDCf1Te4n70hLok=
  file:
   - releases/skywallet-firmware-${TRAVIS_TAG}.bin
   - releases/skywallet-firmware-${TRAVIS_TAG}.bin.asc
   - releases/skywallet-full-no-mem-protect-${COMBINED_VERSION}.bin
   - releases/skywallet-full-no-mem-protect-${COMBINED_VERSION}.bin.asc
   - releases/skywallet-full-mem-protect-${COMBINED_VERSION}.bin
   - releases/skywallet-full-mem-protect-${COMBINED_VERSION}.bin.asc
   - releases/emulator-$(uname -s)-${TRAVIS_TAG}
   - releases/emulator-$(uname -s)-${TRAVIS_TAG}.asc
  skip_cleanup: true
  draft: true
  on:
    repo: denisacostaq/hw
    tags: true
- provider: releases
  api_key:
    secure: vG42CO+JU1gGv2mFl9EIgzHh5f17ceTs9nHJzL2JTGs5bWkMVsaeVB235wHjMsYZ0uQ1DEhk0eoYCq2cS8pl/Q/8TYufSKo0XiSv6ySPUIzYi4YDkAfMnuXlNlP5Adm9UeI+jISp14sbjnHXTD+pBIalAOCaebqGQBtSvIwAkwOnG4arubDiNIoho/q/vHkLRaqiGkgP7pnujtCb1Z4OQCro9FOpMaNcNXsG7LGuabdtvMpzFlzRmvrSzPJiF7f8Db+LjcBkuneeacIg/Bgpd1X2i98Tv9Ytv8IIsd0WrCfKgTp/YYxDS0u1Bn25EGomac0gSvXiYJ1hDtqn58AY1AXuM5ibVJAu5JOBgGqTkRvrLN4WFoRIrUW10i8ArsVxPh5lWJvtjkYNDMtFhHVBCpTyNnTR/OSLGTkRGYBWuoJRW8h3bR6fmP7WrGyVhKIOgklmv6cPGTI6wUAk5KMvFCpHbhATfkTXVj3f0aZEwae7Eho5KgAIPsnKkZlNEq0y+GMj1LMdEE5Leb78gT7dC5R7p/0YD43WPL/YIA3sBAVFYdE0YTa/0jYn5SBFStGskV8vwGwtRopoV4DR6sGfg5SY6ctM5HVAczcm456k1t8rLmSdZ47XZFvcjg5YgV7Eo2D/1IYpAIKlnnfQ0jklcw6tTd6uWDCf1Te4n70hLok=
  file:
   - releases/emulator-$(uname -s)-${TRAVIS_TAG}
   - releases/emulator-$(uname -s)-${TRAVIS_TAG}.asc
  skip_cleanup: true
  draft: true
  on:
    repo: denisacostaq/hw
    tags: true
    condition: $TRAVIS_OS_NAME = "osx"
